### ISSUE TITLE
Tracking: Support Node 20

### ISSUE THREAD

**Issue by joshmgross** [actions/github-script#421]
Actions now supports Node 20 - https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

We should release a new version of this action that uses Node 20 and drop unnecessary dependencies such as `node-fetch`. Since this will be a breaking change, we should also update any other dependencies to their latest versions such as `@actions/github`.

- [x] Update action to Node 20 - https://github.com/actions/github-script/pull/425
- [x] https://github.com/actions/toolkit/issues/1542
- [x] Remove `node-fetch` - https://github.com/actions/github-script/pull/425

**Comment by MikeMcC399** [comment]
@joshmgross 

It will be good to have a new `node20` version as the blog you linked to says that starting Oct 23, 2023 `node16` JavaScript Actions will begin generating deprecation warnings.

**Comment by timogasda** [comment]
@joshmgross  Would be great to leave NodeJS 16 behind soon. Is there any kind of ETA for this fix? Would any contributions help?

**Comment by MikeMcC399** [comment]
There is a note in https://github.com/actions/upload-artifact/issues/444#issuecomment-1779785321 from @joshmgross which says that GitHub is coordinating this update for official GitHub actions, so it's still a Work-In-Progress.

**Comment by joshmgross** [comment]
No ETA at the moment, but it's something we plan to do soon.

https://github.com/actions/github-script/pull/425#issuecomment-1761977036 is blocking the upgrade right now, I haven't had time to identify what is breaking the `previews` input for preview headers. External contributions are welcome if you'd like to look into that.

**Comment by joshmgross** [comment]
Released as part of https://github.com/actions/github-script/releases/tag/v7.0.0
